### PR TITLE
Interpreter module renamed to scenario-compiler

### PR DESCRIPTION
**Pull request by arkadius**
## Checklist before merge
- [ ] Related issue ID is placed at the beginning of PR title in \[brackets\] (can be GH issue or Nu Jira issue)
- [ ] Code is cleaned from temporary changes and commented out lines
- [ ] Parts of the code that are not easy to understand are documented in the code
- [ ] Changes are covered by automated tests
- [ ] Showcase in dev-application.conf added to demonstrate the feature
- [ ] Documentation added or updated
- [ ] Added entry in _Changelog.md_ describing the change from the perspective of a public distribution user
- [ ] Added _MigrationGuide.md_ entry in the appropriate subcategory if introducing a breaking change
- [ ] Verify that PR will be squashed during merge

### CODE REVIEW

**Comment by pielas** [comment]
Maybe it would be good to add a comment like `Due to legacy reasons, this class is named after an Interpreter. However, in new terminology, this is a Scenario Compiler` in places like this https://github.com/TouK/nussknacker/blob/8675b11208669323dc61da70df4a0fc0fb5de2de/scenario-compiler/src/main/scala/pl/touk/nussknacker/engine/Interpreter.scala#L24

**Comment by arkadius** [comment]
> Maybe it would be good to add a comment like `Due to legacy reasons, this class is named after an Interpreter. However, in new terminology, this is a Scenario Compiler` in places like this
> 
> https://github.com/TouK/nussknacker/blob/8675b11208669323dc61da70df4a0fc0fb5de2de/scenario-compiler/src/main/scala/pl/touk/nussknacker/engine/Interpreter.scala#L24
> 
> WDYT?

This class is the the interpreter. Take a look that the public method `interpret` takes node and `Context` (of variables) and returns the new `Context` (of variables). 

The big picture is that both the `designer` module and runtime modules use `ProcessCompiler` - it is the entrypoint class in the new `scenario-compiler` module. The compiler as a compilation result returns parts of the scenario graph that are interpreted only on the `runtime` side. So in fact, we have the `interpreter`. With a little bit of effort we could move the `interpter` into the separate module that would be used only by `runtime` modules. I can add a TODO for that. WDYT?

**Comment by pielas** [comment]
> > Maybe it would be good to add a comment like `Due to legacy reasons, this class is named after an Interpreter. However, in new terminology, this is a Scenario Compiler` in places like this
> > https://github.com/TouK/nussknacker/blob/8675b11208669323dc61da70df4a0fc0fb5de2de/scenario-compiler/src/main/scala/pl/touk/nussknacker/engine/Interpreter.scala#L24
> > 
> > WDYT?
> 
> This class is the the interpreter. Take a look that the public method `interpret` takes node and `Context` (of variables) and returns the new `Context` (of variables).
> 
> The big picture is that both the `designer` module and runtime modules use `ProcessCompiler` - it is the entrypoint class in the new `scenario-compiler` module. The compiler as a compilation result returns parts of the scenario graph that are interpreted only on the `runtime` side. So in fact, we have the `interpreter`. With a little bit of effort we could move the `interpter` into the separate module that would be used only by `runtime` modules. I can add a TODO for that. WDYT?

at first glance I thought that this is compiler. Leaving a TODO sounds good

**Comment by arkadius** [comment]
> > > Maybe it would be good to add a comment like `Due to legacy reasons, this class is named after an Interpreter. However, in new terminology, this is a Scenario Compiler` in places like this
> > > https://github.com/TouK/nussknacker/blob/8675b11208669323dc61da70df4a0fc0fb5de2de/scenario-compiler/src/main/scala/pl/touk/nussknacker/engine/Interpreter.scala#L24
> > > 
> > > WDYT?
> > 
> > 
> > This class is the the interpreter. Take a look that the public method `interpret` takes node and `Context` (of variables) and returns the new `Context` (of variables).
> > The big picture is that both the `designer` module and runtime modules use `ProcessCompiler` - it is the entrypoint class in the new `scenario-compiler` module. The compiler as a compilation result returns parts of the scenario graph that are interpreted only on the `runtime` side. So in fact, we have the `interpreter`. With a little bit of effort we could move the `interpter` into the separate module that would be used only by `runtime` modules. I can add a TODO for that. WDYT?
> 
> at first glance I thought that this is compiler. Leaving a TODO sounds good

Ok, done

**Review by pielas — APPROVED** [review]
LGTM!

**Pull request merged**
