### PR TITLE
🎄🎅🏼🎁 a really important and needed ux change

### PR DESCRIPTION
**Pull request by JulianWielga**
Just had to ... can't wait for the reviews 😂

### CODE REVIEW

**Review by lciolecki — APPROVED** [review]
Great!

**Comment by dswiecki** [comment]
-1

**Review by dswiecki — CHANGES_REQUESTED** [review]
i'm not sure if we can merge this Julek :)

**Comment by arkadius** [comment]
Christmas are canceled this year because of Covid :mask: :stuck_out_tongue_winking_eye:  - closing it

**Pull request closed without merging**
