### PR TITLE
Fix read-only presentation

### PR DESCRIPTION
**Pull request by PPiedel**
This resolves #577

### CODE REVIEW

**Comment by lciolecki** [comment]
Please change all js file to tsx :)

**Comment by arkadius** [comment]
Does it fix all mentioned in this comment things: https://github.com/TouK/nussknacker/issues/192#issuecomment-575562900 ?

**Comment by PPiedel** [comment]
> Please change all touched js file to tsx :)

Done

**Comment by PPiedel** [comment]
> Does it fix all mentioned in this comment things: [#192 (comment)](https://github.com/TouK/nussknacker/issues/192#issuecomment-575562900) ?

Yes

**Comment by PPiedel** [comment]
Due to multiple errors with external libraries like lodash / moment I decided not to change files to tsx right now

**Pull request merged**
